-- ==========================================================================
-- TestVault - Database Schema
-- ==========================================================================
--
-- This schema was reverse-engineered from the existing Node.js application's
-- SQL usage - there was no schema file, migration, or DDL anywhere in the
-- original repository. Every column below is backed by an actual read or
-- write in the current codebase (file:line references given per table).
-- Nothing here is speculative.
--
-- This schema is the shared contract between:
--   - The new ASP.NET Core app (TestVault.Web/Application/Infrastructure)
--   - The EXISTING, unchanged Node.js/Playwright test engine
--     (reporters/sql-reporter.js, scripts/run-tests.js), which keeps
--     writing to these exact tables/columns after the web dashboard is
--     migrated (see the migration plan's "test-execution bridge" phase).
-- Do not rename columns/tables without also updating sql-reporter.js and
-- run-tests.js - they are not part of this migration.
--
-- Script is idempotent (safe to re-run) via existence checks, matching the
-- defensive style already used in the app's own SQL (see analysis.js's
-- MERGE and run-tests.js's IF NOT EXISTS).
-- ==========================================================================

-- ==========================================================================
-- Table: test_runs
-- One row per Playwright test execution ("run"), created when a run starts
-- and updated when it finishes.
--
-- Evidence:
--   INSERT (initial, status='running'):
--     reporters/sql-reporter.js:26-32  (onBegin)
--     scripts/run-tests.js:22-33       (guarded INSERT, IF NOT EXISTS)
--   UPDATE (on completion):
--     reporters/sql-reporter.js:97-113 (onEnd - finished_at, status,
--                                        passed, failed, skipped, duration_ms)
--   SELECT / aggregate usage:
--     backend/routes/runs.js:12-65     (dashboard summary + 14-day trend,
--                                        filtered on started_at, status)
--     backend/routes/runs.js:70-81     (run list, ORDER BY started_at DESC)
--     backend/routes/runs.js:86-119    (run detail by id)
-- ==========================================================================
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'test_runs')
BEGIN
    CREATE TABLE test_runs
    (
        -- crypto.randomUUID() string, generated by the Node runner/reporter
        -- - stored as VARCHAR (the app never uses SQL Server's
        -- UNIQUEIDENTIFIER type: mssql calls use sql.VarChar for this id).
        id              VARCHAR(64)     NOT NULL,

        total           INT             NOT NULL CONSTRAINT DF_TestRuns_Total       DEFAULT (0),
        passed          INT             NOT NULL CONSTRAINT DF_TestRuns_Passed      DEFAULT (0),
        failed          INT             NOT NULL CONSTRAINT DF_TestRuns_Failed      DEFAULT (0),
        skipped         INT             NOT NULL CONSTRAINT DF_TestRuns_Skipped     DEFAULT (0),

        -- 'manual' | 'scheduler' - see TriggeredBy enum
        triggered_by    VARCHAR(20)     NOT NULL,

        -- e.g. 'test' (process.env.NODE_ENV) - free text today, not an enum
        environment     VARCHAR(50)     NOT NULL,

        -- Playwright project name, e.g. 'chromium'
        browser         VARCHAR(50)     NOT NULL CONSTRAINT DF_TestRuns_Browser     DEFAULT ('chromium'),

        -- 'running' | 'passed' | 'failed' - see RunStatus enum
        status          VARCHAR(20)     NOT NULL CONSTRAINT DF_TestRuns_Status      DEFAULT ('running'),

        -- Never set explicitly in either INSERT statement -> relies on this
        -- column default, exactly like the app's own GETDATE() calls elsewhere.
        started_at      DATETIME        NOT NULL CONSTRAINT DF_TestRuns_StartedAt   DEFAULT (GETDATE()),

        -- NULL while status = 'running'; set once by the onEnd UPDATE.
        finished_at     DATETIME        NULL,

        -- NULL while status = 'running'; set once by the onEnd UPDATE.
        duration_ms     BIGINT          NULL,

        CONSTRAINT PK_TestRuns PRIMARY KEY CLUSTERED (id)
    );
END
GO

-- Dashboard summary/trend queries filter and group by date on started_at,
-- and the run list orders by it descending - runs.js:24, 49-52, 75.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_TestRuns_StartedAt')
    CREATE NONCLUSTERED INDEX IX_TestRuns_StartedAt ON test_runs (started_at DESC);
GO

-- Both the summary and trend queries filter WHERE status != 'running' -
-- runs.js:25, 50.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_TestRuns_Status')
    CREATE NONCLUSTERED INDEX IX_TestRuns_Status ON test_runs (status);
GO

-- ==========================================================================
-- Table: test_cases
-- One row per individual Playwright test result within a run.
--
-- Evidence:
--   INSERT: reporters/sql-reporter.js:62-69 (onTestEnd) - columns list is
--     exactly (run_id, title, status, duration_ms, browser, worker_index,
--     retry_count, error_message, screenshot, video, trace); "id" and
--     "created_at" are never supplied -> IDENTITY id + defaulted timestamp.
--   error_message is explicitly truncated to 2000 chars before insert:
--     reporters/sql-reporter.js:40 -> NVARCHAR(2000) below is not arbitrary.
--   SELECT usage:
--     backend/routes/runs.js:94-105   (tc.* + LEFT JOIN ai_analysis, by run_id,
--                                       ORDER BY tc.created_at ASC)
--     backend/routes/tests.js:6-25    (WHERE tc.status = 'failed')
--     backend/routes/tests.js:28-41   (GROUP BY title, AVG(duration_ms))
--     backend/routes/analysis.js:11-13 (SELECT * WHERE id = @id, sql.Int)
-- ==========================================================================
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'test_cases')
BEGIN
    CREATE TABLE test_cases
    (
        -- Never supplied on INSERT and referenced elsewhere via sql.Int
        -- (analysis.js:12) -> IDENTITY integer PK, not a generated string id.
        id              INT             IDENTITY(1,1)   NOT NULL,

        run_id          VARCHAR(64)     NOT NULL,

        -- test.titlePath().join(' > ') can be a long combined path
        title           NVARCHAR(500)   NOT NULL,

        -- 'passed' | 'failed' | 'skipped' | 'timedOut' - see TestCaseStatus
        -- enum (note the exact camelCase "timedOut", inherited from
        -- Playwright's own TestStatus values - sql-reporter.js:86).
        status          VARCHAR(20)     NOT NULL,

        duration_ms     INT             NOT NULL CONSTRAINT DF_TestCases_DurationMs DEFAULT (0),

        -- Frontend renders this defensively (t.browser || '-'), so it is
        -- treated as nullable rather than assumed always populated.
        browser         VARCHAR(50)     NULL,

        worker_index    INT             NOT NULL CONSTRAINT DF_TestCases_WorkerIndex DEFAULT (0),
        retry_count     INT             NOT NULL CONSTRAINT DF_TestCases_RetryCount  DEFAULT (0),

        -- Truncated to 2000 chars by the app before insert (sql-reporter.js:40).
        error_message   NVARCHAR(2000)  NULL,

        -- Playwright attachment paths; only present when the test failed.
        screenshot      NVARCHAR(500)   NULL,
        video           NVARCHAR(500)   NULL,
        trace           NVARCHAR(500)   NULL,

        -- Never supplied on INSERT; ordered on directly (runs.js:104)
        -- -> relies on this column default.
        created_at      DATETIME        NOT NULL CONSTRAINT DF_TestCases_CreatedAt DEFAULT (GETDATE()),

        CONSTRAINT PK_TestCases PRIMARY KEY CLUSTERED (id)
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_TestCases_TestRuns'
)
    ALTER TABLE test_cases
        ADD CONSTRAINT FK_TestCases_TestRuns
        FOREIGN KEY (run_id) REFERENCES test_runs (id);
GO

-- Every run-detail and failed-tests query filters/joins on run_id -
-- runs.js:94-105, tests.js:6-25.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_TestCases_RunId')
    CREATE NONCLUSTERED INDEX IX_TestCases_RunId ON test_cases (run_id);
GO

-- tests.js:6-25 filters WHERE tc.status = 'failed'.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_TestCases_Status')
    CREATE NONCLUSTERED INDEX IX_TestCases_Status ON test_cases (status);
GO

-- ==========================================================================
-- Table: ai_analysis
-- AI (Claude API) failure analysis for a single test case. One-to-one with
-- test_cases: analysis.js's MERGE matches solely on test_case_id and never
-- references any other key, so test_case_id is both the primary key and the
-- foreign key here, not a separate surrogate id.
--
-- Evidence: backend/routes/analysis.js:58-72 (MERGE ... USING (VALUES
-- (@testCaseId)) ... ON target.test_case_id = source.test_case_id).
-- The INSERT branch does not set analyzed_at explicitly (only the UPDATE
-- branch does, via GETDATE()) - a column default is required for the
-- first-analysis case to be timestamped at all, which is what is modeled
-- below.
-- ==========================================================================
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ai_analysis')
BEGIN
    CREATE TABLE ai_analysis
    (
        test_case_id    INT             NOT NULL,

        -- AI-generated free text, not length-bounded by the app - MAX avoids
        -- silently truncating a model response.
        root_cause      NVARCHAR(MAX)   NOT NULL,
        fix_suggestion  NVARCHAR(MAX)   NOT NULL,

        analyzed_at     DATETIME        NOT NULL CONSTRAINT DF_AiAnalysis_AnalyzedAt DEFAULT (GETDATE()),

        CONSTRAINT PK_AiAnalysis PRIMARY KEY CLUSTERED (test_case_id)
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AiAnalysis_TestCases'
)
    ALTER TABLE ai_analysis
        ADD CONSTRAINT FK_AiAnalysis_TestCases
        FOREIGN KEY (test_case_id) REFERENCES test_cases (id);
GO
