name: Deploy TestVault IIS


on:
  push:
    branches:
      - main


concurrency:
  group: testvault-deployment
  cancel-in-progress: false


jobs:

  deploy:

    runs-on: self-hosted


    env:

      APP_NAME: TestVault

      BASE_PATH: E:\AllWebApplication\TestVault

      RELEASE_PATH: E:\AllWebApplication\TestVault\Releases

      CURRENT_PATH: E:\AllWebApplication\TestVault\Current

      BACKUP_PATH: E:\AllWebApplication\TestVault\Backup

      HEALTH_URL: http://localhost/



    steps:


    # ======================================
    # Checkout
    # ======================================

    - name: Checkout Code

      uses: actions/checkout@v4

      with:
        fetch-depth: 1



    # ======================================
    # Repository Check
    # ======================================

    - name: Check Repository Structure

      shell: powershell

      run: |

        Write-Host "Workspace:"
        Write-Host "${{ github.workspace }}"


        Write-Host "Finding Solution"

        $solution = Get-ChildItem `
          "${{ github.workspace }}" `
          -Recurse `
          -Filter *.sln |
          Select-Object -First 1


        if($null -eq $solution)
        {
            throw "Solution file not found"
        }


        Write-Host "Solution Found:"
        Write-Host $solution.FullName



        Write-Host "Finding Project"


        $project = Get-ChildItem `
          "${{ github.workspace }}" `
          -Recurse `
          -Filter *.csproj |
          Select-Object -First 1



        if($null -eq $project)
        {
            throw "Project file not found"
        }



        Write-Host "Project Found:"
        Write-Host $project.FullName



        "SOLUTION=$($solution.FullName)" >> $env:GITHUB_ENV

        "PROJECT=$($project.FullName)" >> $env:GITHUB_ENV





    # ======================================
    # Environment Check
    # ======================================

    - name: Environment Check

      shell: powershell

      run: |


        Write-Host "Checking .NET"


        $dotnet = Get-Command dotnet.exe `
          -ErrorAction SilentlyContinue



        if($null -eq $dotnet)
        {
            throw ".NET SDK not found"
        }



        dotnet --version



        Write-Host ".NET OK"





    # ======================================
    # Restore
    # ======================================

    - name: Restore NuGet Packages

      shell: powershell

      run: |


        Write-Host "Restore Started"


        dotnet restore "${{ env.SOLUTION }}"



        if($LASTEXITCODE -ne 0)
        {
            throw "Restore Failed"
        }


        Write-Host "Restore Completed"





    # ======================================
    # Build
    # ======================================

    - name: Build Application

      shell: powershell


      run: |


        Write-Host "Build Started"



        dotnet build "${{ env.SOLUTION }}" `
          --configuration Release `
          --no-restore



        if($LASTEXITCODE -ne 0)
        {
            throw "Build Failed"
        }



        Write-Host "Build Completed"





    # ======================================
    # Prepare Folder
    # ======================================

    - name: Prepare Deployment Folder


      shell: powershell


      run: |


        New-Item `
          -ItemType Directory `
          -Path "${{env.RELEASE_PATH}}" `
          -Force | Out-Null


        New-Item `
          -ItemType Directory `
          -Path "${{env.CURRENT_PATH}}" `
          -Force | Out-Null


        New-Item `
          -ItemType Directory `
          -Path "${{env.BACKUP_PATH}}" `
          -Force | Out-Null






    # ======================================
    # Create Release
    # ======================================


    - name: Create Release


      shell: powershell


      run: |


        $release = Join-Path `
          "${{env.RELEASE_PATH}}" `
          "Release_$(Get-Date -Format yyyyMMdd_HHmmss)"



        New-Item `
          -ItemType Directory `
          -Path $release `
          -Force | Out-Null



        "NEW_RELEASE=$release" >> $env:GITHUB_ENV



        Write-Host $release






    # ======================================
    # Publish
    # ======================================


    - name: Publish Application


      shell: powershell


      run: |


        dotnet publish "${{env.PROJECT}}" `
          --configuration Release `
          --output "${{env.NEW_RELEASE}}" `
          --no-build



        if($LASTEXITCODE -ne 0)
        {
            throw "Publish Failed"
        }



        Write-Host "Publish Completed"







    # ======================================
    # Backup Current
    # ======================================


    - name: Backup Current Version


      shell: powershell


      run: |


        $files = Get-ChildItem `
          "${{env.CURRENT_PATH}}" `
          -Force `
          -ErrorAction SilentlyContinue



        if($files.Count -gt 0)
        {


          $backup = Join-Path `
            "${{env.BACKUP_PATH}}" `
            "Backup_$(Get-Date -Format yyyyMMdd_HHmmss)"



          New-Item `
            -ItemType Directory `
            -Path $backup `
            -Force | Out-Null



          Copy-Item `
            "${{env.CURRENT_PATH}}\*" `
            $backup `
            -Recurse `
            -Force



          "OLD_BACKUP=$backup" >> $env:GITHUB_ENV



        }





    # ======================================
    # Deploy
    # ======================================


    - name: Deploy Release


      shell: powershell


      run: |


        Write-Host "Deploying"



        Set-Content `
          "${{env.CURRENT_PATH}}\app_offline.htm" `
          "Updating Application"



        Start-Sleep -Seconds 10



        Remove-Item `
          "${{env.CURRENT_PATH}}\*" `
          -Recurse `
          -Force



        Copy-Item `
          "${{env.NEW_RELEASE}}\*" `
          "${{env.CURRENT_PATH}}" `
          -Recurse `
          -Force



        Remove-Item `
          "${{env.CURRENT_PATH}}\app_offline.htm" `
          -Force



        Write-Host "Deployment Completed"







    # ======================================
    # Health Check
    # ======================================


    - name: Health Check


      shell: powershell


      run: |


        Start-Sleep -Seconds 20



        try
        {

          $response = Invoke-WebRequest `
            "${{env.HEALTH_URL}}" `
            -UseBasicParsing



          if($response.StatusCode -ge 400)
          {
              throw "Application Failed"
          }



          Write-Host "Application Healthy"


        }

        catch
        {

          throw "Health Check Failed"

        }





    # ======================================
    # Cleanup
    # ======================================


    - name: Cleanup Old Releases


      shell: powershell


      run: |


        Get-ChildItem "${{env.RELEASE_PATH}}" `
          -Directory |
          Sort-Object CreationTime -Descending |
          Select-Object -Skip 5 |
          Remove-Item -Recurse -Force



        Get-ChildItem "${{env.BACKUP_PATH}}" `
          -Directory |
          Sort-Object CreationTime -Descending |
          Select-Object -Skip 5 |
          Remove-Item -Recurse -Force



        Write-Host "Cleanup Completed"
